import { useEffect, useState } from 'react'
import { Footer, Header, Link } from '../components/Layout'
import { goTo } from '../components/navigation'
import { getProductoId, getProductoValue, getProductos } from '../api/productos'
import { createRecurso, getRecursoId, getRecursoValue, getRecursos, getResourceList, updateRecurso } from '../api/recursos'

export default function RegistroPedidoPage() {
  const id = new URLSearchParams(window.location.search).get('id')
  const [productos, setProductos] = useState([])
  const [values, setValues] = useState({ cliente: '', fecha: '', producto_id: '', cantidad: '', prioridad: '', estado: '' })
  const [cargando, setCargando] = useState(Boolean(id))
  const [error, setError] = useState('')
  useEffect(() => { getProductos().then(response => setProductos(getResourceList(response))).catch(apiError => setError(apiError.message)) }, [])
  useEffect(() => { if (!id) return; getRecursos('pedidos').then(response => { const pedido = getResourceList(response).find(item => String(getRecursoId(item)) === id); if (pedido) setValues({ cliente: getRecursoValue(pedido, 'nombre_cliente', 'cliente') || '', fecha: getRecursoValue(pedido, 'fecha') || '', producto_id: getRecursoValue(pedido, 'producto_id') || getProductoId(getRecursoValue(pedido, 'producto') || {}), cantidad: getRecursoValue(pedido, 'cantidad') || '', prioridad: getRecursoValue(pedido, 'prioridad') || '', estado: getRecursoValue(pedido, 'estado') || '' }) }).catch(apiError => setError(apiError.message)).finally(() => setCargando(false)) }, [id])
  const change = field => event => setValues(current => ({ ...current, [field]: event.target.value }))
  const submit = async event => { event.preventDefault(); try { const data = { nombre_cliente: values.cliente, fecha: values.fecha, producto_id: Number(values.producto_id), cantidad: Number(values.cantidad), prioridad: values.prioridad, estado: values.estado }; if (id) await updateRecurso('pedidos', id, data); else await createRecurso('pedidos', data); goTo('/pedidos') } catch (apiError) { setError(apiError.message) } }
  return <div className="pagina-dashboard"><Header active="pedidos" /><main className="contenido-dashboard contenido-productos"><div className="contenedor"><section className="encabezado-productos"><div><p className="etiqueta">Gestión de pedidos</p><h1>{id ? 'Editar pedido' : 'Registrar pedido'}</h1><p>Ingresa la información del nuevo pedido.</p></div><Link className="boton" href="/pedidos">Volver a pedidos</Link></section><section className="panel-dashboard registro-producto"><div className="encabezado-panel"><p className="etiqueta">Nuevo registro</p><h2>Datos del pedido</h2></div><form className="formulario-pedido" onSubmit={submit}>{error && <p role="alert">{error}</p>}<div className="campo-producto"><label>Cliente</label><input value={values.cliente} onChange={change('cliente')} required /></div><div className="campo-producto"><label>Fecha solicitada</label><input type="date" value={values.fecha} onChange={change('fecha')} required /></div><div className="campo-producto"><label>Producto</label><select value={values.producto_id} onChange={change('producto_id')} required><option value="">Seleccionar producto</option>{productos.map(producto => <option key={getProductoId(producto)} value={getProductoId(producto)}>{getProductoValue(producto, 'nombre', 'name', 'producto')}</option>)}</select></div><div className="campo-producto"><label>Cantidad</label><input type="number" min="1" value={values.cantidad} onChange={change('cantidad')} required /></div><div className="campo-producto"><label>Prioridad</label><select value={values.prioridad} onChange={change('prioridad')} required><option value="">Seleccionar prioridad</option><option>Alta</option><option>Normal</option><option>Baja</option></select></div><div className="campo-producto"><label>Estado</label><select value={values.estado} onChange={change('estado')} required><option value="">Seleccionar estado</option><option>Pendiente</option><option>Atendido</option><option>Cancelado</option></select></div><div className="acciones-formulario"><button className="boton" type="submit" disabled={cargando}>{id ? 'Actualizar' : 'Guardar pedido'}</button><button className="boton boton-cancelar" type="reset">Limpiar</button></div></form></section></div></main><Footer /></div>
}
